/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewPasswordEntryForm.java
 *
 * Created on Apr 2, 2014, 12:06:37 PM
 */
package com.blazartech.products.crypto.maintain.gui;

import javax.swing.JPanel;

/**
 * a simple form to allow input of a new password.
 * 
 * @author aar1069
 * @version $Id: NewPasswordEntryForm.java 531 2014-04-21 18:31:59Z aar1069 $
 */
public class NewPasswordEntryForm extends JPanel {

    public String getPassword() {
        return new String(passwordField.getPassword());
    }
    
    protected String resource;
    public static final String PROP_RESOURCE = "resource";

    /**
     * Get the value of resource
     *
     * @return the value of resource
     */
    public String getResource() {
        return resource;
    }

    /**
     * Set the value of resource
     *
     * @param resource new value of resource
     */
    public void setResource(String resource) {
        String oldResource = this.resource;
        this.resource = resource;
        firePropertyChange(PROP_RESOURCE, oldResource, resource);
    }

    protected String userID;
    public static final String PROP_USERID = "userID";

    /**
     * Get the value of userID
     *
     * @return the value of userID
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Set the value of userID
     *
     * @param userID new value of userID
     */
    public void setUserID(String userID) {
        String oldUserID = this.userID;
        this.userID = userID;
        firePropertyChange(PROP_USERID, oldUserID, userID);
    }

    /** Creates new form NewPasswordEntryForm */
    public NewPasswordEntryForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resourceLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Enter new password for ");
        jPanel2.add(jLabel1);
        jPanel2.add(userIDLabel);

        jLabel2.setText("/");
        jPanel2.add(jLabel2);
        jPanel2.add(resourceLabel);

        add(jPanel2, java.awt.BorderLayout.NORTH);
        add(passwordField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        if (evt.getPropertyName().equals(PROP_RESOURCE)) {
            resourceLabel.setText(getResource());
        } else if (evt.getPropertyName().equals(PROP_USERID)) {
            userIDLabel.setText(getUserID());
        }
    }//GEN-LAST:event_formPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel resourceLabel;
    private javax.swing.JLabel userIDLabel;
    // End of variables declaration//GEN-END:variables
}
